scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['goapp:8080']
      - targets: ['goapp2:8181']
      - targets: ['goapp3:8282']
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']