{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_memory_usage", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization{process_cpu_state=\"user\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} | trace_id=~\"\""
    }
   ]
  }
 ]
}